"""fix_client_relations

Revision ID: 111cc21b18bf
Revises: 
Create Date: 2026-02-20 17:52:27.359467

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '111cc21b18bf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cabinets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('raison_sociale', sa.String(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=False),
    sa.Column('code_postal', sa.String(), nullable=True),
    sa.Column('ville', sa.String(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('site_web', sa.String(), nullable=True),
    sa.Column('logo_url', sa.String(), nullable=True),
    sa.Column('numero_agrement', sa.String(), nullable=True),
    sa.Column('juridiction_rattachement', sa.String(), nullable=True),
    sa.Column('chambre_departementale', sa.String(), nullable=True),
    sa.Column('actif', sa.Boolean(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=True),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('numero_agrement')
    )
    op.create_index(op.f('ix_cabinets_email'), 'cabinets', ['email'], unique=False)
    op.create_index(op.f('ix_cabinets_id'), 'cabinets', ['id'], unique=False)
    op.create_index(op.f('ix_cabinets_nom'), 'cabinets', ['nom'], unique=False)
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cabinet', sa.Integer(), nullable=False),
    sa.Column('type_client', sa.Enum('PARTICULIER', 'AVOCAT', 'ENTREPRISE', 'JURIDICTION', name='typeclient'), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('prenom', sa.String(), nullable=True),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('telephone', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('siret', sa.String(length=14), nullable=True),
    sa.Column('representant_legal', sa.String(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_cabinet'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clients_email'), 'clients', ['email'], unique=False)
    op.create_index(op.f('ix_clients_id'), 'clients', ['id'], unique=False)
    op.create_index(op.f('ix_clients_nom'), 'clients', ['nom'], unique=False)
    op.create_index(op.f('ix_clients_type_client'), 'clients', ['type_client'], unique=False)
    op.create_table('statistics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cabinet', sa.Integer(), nullable=False),
    sa.Column('type_statistique', sa.Enum('CABINET', 'DOSSIER', 'FINANCIER', 'UTILISATEUR', 'ACTIVITE', name='typestatistique'), nullable=False),
    sa.Column('periode', sa.Enum('JOUR', 'SEMAINE', 'MOIS', 'TRIMESTRE', 'ANNEE', name='periodestatistique'), nullable=False),
    sa.Column('date_debut', sa.Date(), nullable=False),
    sa.Column('date_fin', sa.Date(), nullable=False),
    sa.Column('nom_metrique', sa.String(length=100), nullable=False),
    sa.Column('valeur_numerique', sa.Float(), nullable=True),
    sa.Column('valeur_texte', sa.String(length=500), nullable=True),
    sa.Column('details_json', sa.String(), nullable=True),
    sa.Column('calcule_le', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['id_cabinet'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_statistics_id'), 'statistics', ['id'], unique=False)
    op.create_table('utilisateurs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cabinet', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('nom', sa.String(length=100), nullable=False),
    sa.Column('prenom', sa.String(length=100), nullable=False),
    sa.Column('telephone', sa.String(length=20), nullable=True),
    sa.Column('mot_de_passe_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'HUISSIER', 'CLERC', 'ASSISTANT', 'SECRETAIRE', name='roleenum'), nullable=False),
    sa.Column('actif', sa.Boolean(), nullable=False),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=True),
    sa.Column('derniere_connexion', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cabinet'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_utilisateurs_email'), 'utilisateurs', ['email'], unique=True)
    op.create_index(op.f('ix_utilisateurs_id'), 'utilisateurs', ['id'], unique=False)
    op.create_index(op.f('ix_utilisateurs_id_cabinet'), 'utilisateurs', ['id_cabinet'], unique=False)
    op.create_index(op.f('ix_utilisateurs_nom'), 'utilisateurs', ['nom'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_utilisateur', sa.Integer(), nullable=True),
    sa.Column('id_cabinet', sa.Integer(), nullable=True),
    sa.Column('action', sa.Enum('CREATE', 'UPDATE', 'DELETE', 'VIEW', 'LOGIN', 'LOGOUT', 'EXPORT', 'PRINT', name='actiontype'), nullable=False),
    sa.Column('entity_type', sa.Enum('CABINET', 'CLIENT', 'DOSSIER', 'ACTE', 'PARTIE', 'DOCUMENT', 'PAIEMENT', 'UTILISATEUR', 'ARCHIVE', name='entitytype'), nullable=False),
    sa.Column('entity_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('donnees_avant', sa.JSON(), nullable=True),
    sa.Column('donnees_apres', sa.JSON(), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('date_action', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cabinet'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_date_action'), 'audit_logs', ['date_action'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_table('dossiers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_dossier', sa.String(length=50), nullable=False),
    sa.Column('objet', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type_dossier', sa.Enum('CONTENTIEUX', 'RECOUVREMENT', 'CONSTAT', 'SIGNIFICATION', 'SAISIE', 'EXPULSION', 'AUTRE', name='typedossier'), nullable=False),
    sa.Column('statut', sa.Enum('NOUVEAU', 'EN_COURS', 'EN_ATTENTE', 'TERMINE', 'ARCHIVE', 'ANNULE', name='statutdossier'), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=True),
    sa.Column('cabinet_id', sa.Integer(), nullable=False),
    sa.Column('utilisateur_responsable_id', sa.Integer(), nullable=True),
    sa.Column('date_ouverture', sa.DateTime(), nullable=False),
    sa.Column('date_cloture', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('date_modification', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cabinet_id'], ['cabinets.id'], ),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['utilisateur_responsable_id'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dossiers_id'), 'dossiers', ['id'], unique=False)
    op.create_index(op.f('ix_dossiers_numero_dossier'), 'dossiers', ['numero_dossier'], unique=True)
    op.create_index(op.f('ix_dossiers_utilisateur_responsable_id'), 'dossiers', ['utilisateur_responsable_id'], unique=False)
    op.create_table('affectations_dossier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dossier', sa.Integer(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('affecte_par', sa.Integer(), nullable=True),
    sa.Column('date_affectation', sa.DateTime(), nullable=True),
    sa.Column('date_fin_affectation', sa.DateTime(), nullable=True),
    sa.Column('est_actif', sa.Boolean(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['affecte_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['id_dossier'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affectations_dossier_id'), 'affectations_dossier', ['id'], unique=False)
    op.create_table('agenda',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('reference', sa.String(length=50), nullable=False),
    sa.Column('id_dossier', sa.Integer(), nullable=True),
    sa.Column('id_utilisateur', sa.Integer(), nullable=False),
    sa.Column('id_client', sa.Integer(), nullable=True),
    sa.Column('titre', sa.String(length=200), nullable=False),
    sa.Column('type_rdv', sa.Enum('SIGNIFICATION', 'CONSTAT', 'SAISIE', 'AUDIENCE', 'CLIENT', 'INTERNE', 'AUTRE', name='typerendezvous'), nullable=False),
    sa.Column('statut', sa.Enum('PLANIFIE', 'CONFIRME', 'EN_COURS', 'TERMINE', 'ANNULE', 'REPORTE', name='statutrendezvous'), nullable=False),
    sa.Column('priorite', sa.Enum('BASSE', 'NORMALE', 'HAUTE', 'URGENTE', name='prioriterendezvous'), nullable=False),
    sa.Column('date_debut', sa.DateTime(), nullable=False),
    sa.Column('date_fin', sa.DateTime(), nullable=False),
    sa.Column('duree_minutes', sa.Integer(), nullable=False),
    sa.Column('lieu', sa.String(length=300), nullable=True),
    sa.Column('participants', sa.Text(), nullable=True),
    sa.Column('rappel_active', sa.Boolean(), nullable=True),
    sa.Column('rappel_minutes_avant', sa.Integer(), nullable=True),
    sa.Column('notification_envoyee', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('notes_internes', sa.Text(), nullable=True),
    sa.Column('annule', sa.Boolean(), nullable=True),
    sa.Column('motif_annulation', sa.Text(), nullable=True),
    sa.Column('date_annulation', sa.DateTime(), nullable=True),
    sa.Column('reporte', sa.Boolean(), nullable=True),
    sa.Column('ancienne_date', sa.DateTime(), nullable=True),
    sa.Column('date_creation', sa.DateTime(), nullable=False),
    sa.Column('date_modification', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['id_client'], ['clients.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_dossier'], ['dossiers.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['id_utilisateur'], ['utilisateurs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agenda_date_debut'), 'agenda', ['date_debut'], unique=False)
    op.create_index(op.f('ix_agenda_id'), 'agenda', ['id'], unique=False)
    op.create_index(op.f('ix_agenda_id_client'), 'agenda', ['id_client'], unique=False)
    op.create_index(op.f('ix_agenda_id_dossier'), 'agenda', ['id_dossier'], unique=False)
    op.create_index(op.f('ix_agenda_id_utilisateur'), 'agenda', ['id_utilisateur'], unique=False)
    op.create_index(op.f('ix_agenda_reference'), 'agenda', ['reference'], unique=True)
    op.create_index(op.f('ix_agenda_statut'), 'agenda', ['statut'], unique=False)
    op.create_index(op.f('ix_agenda_type_rdv'), 'agenda', ['type_rdv'], unique=False)
    op.create_table('archives',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dossier_id', sa.Integer(), nullable=False),
    sa.Column('type_archive', sa.Enum('DOSSIER', 'ACTE', 'DOCUMENT', 'PAIEMENT', name='typearchive'), nullable=False),
    sa.Column('id_reference', sa.Integer(), nullable=False),
    sa.Column('id_cabinet', sa.Integer(), nullable=False),
    sa.Column('donnees_json', sa.Text(), nullable=False),
    sa.Column('raison_archivage', sa.Text(), nullable=True),
    sa.Column('archive_par', sa.Integer(), nullable=True),
    sa.Column('date_archivage', sa.DateTime(), nullable=True),
    sa.Column('date_suppression_prevue', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['archive_par'], ['utilisateurs.id'], ),
    sa.ForeignKeyConstraint(['dossier_id'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['id_cabinet'], ['cabinets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_archives_id'), 'archives', ['id'], unique=False)
    op.create_table('paiements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dossier', sa.Integer(), nullable=False),
    sa.Column('type_paiement', sa.Enum('FRAIS', 'AVANCE', 'RECOUVREMENT', name='typepaiement'), nullable=False),
    sa.Column('montant', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('date_paiement', sa.Date(), nullable=False),
    sa.Column('mode_paiement', sa.Enum('ESPECES', 'CHEQUE', 'VIREMENT', name='modepaiement'), nullable=False),
    sa.Column('reverse_au_client', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['id_dossier'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_paiements_id'), 'paiements', ['id'], unique=False)
    op.create_table('parties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dossier', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('DEBITEUR', 'DESTINATAIRE', 'AUTRE', name='rolepartie'), nullable=False),
    sa.Column('adresse', sa.Text(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['id_dossier'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_parties_id'), 'parties', ['id'], unique=False)
    op.create_table('actes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dossier', sa.Integer(), nullable=False),
    sa.Column('id_evenement', sa.Integer(), nullable=True),
    sa.Column('type_acte', sa.Enum('SIGNIFICATION', 'CONSTAT', 'SAISIE', name='typeacte'), nullable=False),
    sa.Column('date_acte', sa.Date(), nullable=False),
    sa.Column('lieu', sa.String(), nullable=True),
    sa.Column('resultat', sa.Text(), nullable=True),
    sa.Column('observations', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['id_dossier'], ['dossiers.id'], ),
    sa.ForeignKeyConstraint(['id_evenement'], ['agenda.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_actes_id'), 'actes', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_dossier', sa.Integer(), nullable=False),
    sa.Column('id_acte', sa.Integer(), nullable=True),
    sa.Column('type_document', sa.Enum('ACTE', 'COURRIER', 'FACTURE', 'PIECE_JOINTE', 'JUGEMENT', 'AUTRE', name='typedocument'), nullable=False),
    sa.Column('nom_fichier', sa.String(length=255), nullable=False),
    sa.Column('nom_original', sa.String(length=255), nullable=False),
    sa.Column('chemin_fichier', sa.String(length=500), nullable=False),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('taille_octets', sa.BigInteger(), nullable=True),
    sa.Column('date_upload', sa.DateTime(), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['id_acte'], ['actes.id'], ),
    sa.ForeignKeyConstraint(['id_dossier'], ['dossiers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_actes_id'), table_name='actes')
    op.drop_table('actes')
    op.drop_index(op.f('ix_parties_id'), table_name='parties')
    op.drop_table('parties')
    op.drop_index(op.f('ix_paiements_id'), table_name='paiements')
    op.drop_table('paiements')
    op.drop_index(op.f('ix_archives_id'), table_name='archives')
    op.drop_table('archives')
    op.drop_index(op.f('ix_agenda_type_rdv'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_statut'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_reference'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_id_utilisateur'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_id_dossier'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_id_client'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_id'), table_name='agenda')
    op.drop_index(op.f('ix_agenda_date_debut'), table_name='agenda')
    op.drop_table('agenda')
    op.drop_index(op.f('ix_affectations_dossier_id'), table_name='affectations_dossier')
    op.drop_table('affectations_dossier')
    op.drop_index(op.f('ix_dossiers_utilisateur_responsable_id'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_numero_dossier'), table_name='dossiers')
    op.drop_index(op.f('ix_dossiers_id'), table_name='dossiers')
    op.drop_table('dossiers')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_date_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_utilisateurs_nom'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id_cabinet'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_id'), table_name='utilisateurs')
    op.drop_index(op.f('ix_utilisateurs_email'), table_name='utilisateurs')
    op.drop_table('utilisateurs')
    op.drop_index(op.f('ix_statistics_id'), table_name='statistics')
    op.drop_table('statistics')
    op.drop_index(op.f('ix_clients_type_client'), table_name='clients')
    op.drop_index(op.f('ix_clients_nom'), table_name='clients')
    op.drop_index(op.f('ix_clients_id'), table_name='clients')
    op.drop_index(op.f('ix_clients_email'), table_name='clients')
    op.drop_table('clients')
    op.drop_index(op.f('ix_cabinets_nom'), table_name='cabinets')
    op.drop_index(op.f('ix_cabinets_id'), table_name='cabinets')
    op.drop_index(op.f('ix_cabinets_email'), table_name='cabinets')
    op.drop_table('cabinets')
    # ### end Alembic commands ###
