"""add mot_de_passe to dossier

Revision ID: 63abf143e491
Revises: fb98a2be9f26
Create Date: 2026-05-05 10:14:36.806001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63abf143e491'
down_revision: Union[str, None] = 'fb98a2be9f26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
